//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JSplitPane;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
/**
 * @author  Administrator
 * @created February 9, 2017
 */
public class Dispaly extends JFrame {
static Dispaly theuif;

JPanel pnRoot_panel;
JSplitPane sppSplitPane;

JPanel pnLeft;
JButton btNew_image;
JButton btCheck_image;

JPanel pnRight;

JPanel pnImage_display;
JTextArea taComment;
JTextArea taArea1;
/**
 */
public static void main(String args[]) {
   try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
   }
   catch (ClassNotFoundException e) {
   }
   catch (InstantiationException e) {
   }
   catch (IllegalAccessException e) {
   }
   catch (UnsupportedLookAndFeelException e) {
   }
   theuif = new Dispaly();
} 

/**
 */
public Dispaly() {
   super("Watermark");

   pnRoot_panel = new JPanel();
   GridBagLayout gbRoot_panel = new GridBagLayout();
   GridBagConstraints gbcRoot_panel = new GridBagConstraints();
   
   pnRoot_panel.setLayout(gbRoot_panel);
  
   pnRoot_panel.setSize(1000, 1000);

   sppSplitPane = new JSplitPane();
   sppSplitPane.setDividerLocation(170);
   sppSplitPane.setForeground(new Color(0,0,0));
   sppSplitPane.setLastDividerLocation(-1);

   pnLeft = new JPanel();
   GridBagLayout gbLeft = new GridBagLayout();
   GridBagConstraints gbcLeft = new GridBagConstraints();
   pnLeft.setLayout(gbLeft);

   btNew_image = new JButton("New Image");
   gbcLeft.gridx = 0;
   gbcLeft.gridy = 2;
   gbcLeft.gridwidth = 6;
   gbcLeft.gridheight = 3;
   gbcLeft.fill = GridBagConstraints.BOTH;
   gbcLeft.weightx = 1;
   gbcLeft.weighty = 0;
   gbcLeft.anchor = GridBagConstraints.NORTH;
   gbLeft.setConstraints(btNew_image, gbcLeft);
   pnLeft.add(btNew_image);

   btCheck_image = new JButton("Check Image");
   gbcLeft.gridx = 0;
   gbcLeft.gridy = 8;
   gbcLeft.gridwidth = 6;
   gbcLeft.gridheight = 3;
   gbcLeft.fill = GridBagConstraints.BOTH;
   gbcLeft.weightx = 1;
   gbcLeft.weighty = 0;
   gbcLeft.anchor = GridBagConstraints.NORTH;
   gbLeft.setConstraints(btCheck_image, gbcLeft);
   pnLeft.add(btCheck_image);
   sppSplitPane.setLeftComponent(pnLeft);

   pnRight = new JPanel();
   GridBagLayout gbRight = new GridBagLayout();
   GridBagConstraints gbcRight = new GridBagConstraints();
   pnRight.setLayout(gbRight);

   pnImage_display = new JPanel();
   GridBagLayout gbImage_display = new GridBagLayout();
   GridBagConstraints gbcImage_display = new GridBagConstraints();
   pnImage_display.setLayout(gbImage_display);
   gbcRight.gridx = 0;
   gbcRight.gridy = 0;
   gbcRight.gridwidth = 10;
   gbcRight.gridheight = 12;
   gbcRight.fill = GridBagConstraints.BOTH;
   gbcRight.weightx = 1;
   gbcRight.weighty = 0;
   gbcRight.anchor = GridBagConstraints.NORTH;
   gbRight.setConstraints(pnImage_display, gbcRight);
   pnRight.add(pnImage_display);

   taComment = new JTextArea(2,10);
   JScrollPane scpComment = new JScrollPane(taComment);
   gbcRight.gridx = 0;
   gbcRight.gridy = 12;
   gbcRight.gridwidth = 10;
   gbcRight.gridheight = 4;
   gbcRight.fill = GridBagConstraints.BOTH;
   gbcRight.weightx = 1;
   gbcRight.weighty = 1;
   gbcRight.anchor = GridBagConstraints.NORTH;
   gbRight.setConstraints(scpComment, gbcRight);
   pnRight.add(scpComment);
   sppSplitPane.setRightComponent(pnRight);
   gbcRoot_panel.gridx = 0;
   gbcRoot_panel.gridy = 1;
   gbcRoot_panel.gridwidth = 1;
   gbcRoot_panel.gridheight = 1;
   gbcRoot_panel.fill = GridBagConstraints.BOTH;
   gbcRoot_panel.weightx = 1;
   gbcRoot_panel.weighty = 1;
   gbcRoot_panel.anchor = GridBagConstraints.NORTH;
   gbRoot_panel.setConstraints(sppSplitPane, gbcRoot_panel);
   pnRoot_panel.add(sppSplitPane);

   taArea1 = new JTextArea(2,10);
   gbcRoot_panel.gridx = 0;
   gbcRoot_panel.gridy = 0;
   gbcRoot_panel.gridwidth = 1;
   gbcRoot_panel.gridheight = 1;
   gbcRoot_panel.fill = GridBagConstraints.BOTH;
   gbcRoot_panel.weightx = 1;
   gbcRoot_panel.weighty = 1;
   gbcRoot_panel.anchor = GridBagConstraints.NORTH;
   gbRoot_panel.setConstraints(taArea1, gbcRoot_panel);
   pnRoot_panel.add(taArea1);

   setDefaultCloseOperation(EXIT_ON_CLOSE);

   setContentPane(pnRoot_panel);
   
   pack();
   setVisible(true);
} 
} 
