//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JSplitPane;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
/**
 * @author  Administrator
 * @created February 9, 2017
 */
public class ui extends JFrame {
static ui theui;

JPanel pnPanel0;
JSplitPane sppSplitPane1;

JPanel pnPanel4;
JButton btBut0;
JButton btBut1;

JPanel pnPanel5;

JPanel pnPanel6;
JTextArea taArea0;
JTextArea taArea1;
/**
 */
public static void main(String args[]) {
   try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
   }
   catch (ClassNotFoundException e) {
   }
   catch (InstantiationException e) {
   }
   catch (IllegalAccessException e) {
   }
   catch (UnsupportedLookAndFeelException e) {
   }
   theui = new ui();
} 

/**
 */
public ui() {
   super("TITLE");

   pnPanel0 = new JPanel();
   GridBagLayout gbPanel0 = new GridBagLayout();
   GridBagConstraints gbcPanel0 = new GridBagConstraints();
   pnPanel0.setLayout(gbPanel0);

   sppSplitPane1 = new JSplitPane();
   sppSplitPane1.setDividerLocation(168);
   sppSplitPane1.setForeground(new Color(0,0,0));
   sppSplitPane1.setLastDividerLocation(-1);

   pnPanel4 = new JPanel();
   GridBagLayout gbPanel4 = new GridBagLayout();
   GridBagConstraints gbcPanel4 = new GridBagConstraints();
   pnPanel4.setLayout(gbPanel4);

   btBut0 = new JButton("New Image");
   gbcPanel4.gridx = 0;
   gbcPanel4.gridy = 2;
   gbcPanel4.gridwidth = 6;
   gbcPanel4.gridheight = 3;
   gbcPanel4.fill = GridBagConstraints.BOTH;
   gbcPanel4.weightx = 1;
   gbcPanel4.weighty = 0;
   gbcPanel4.anchor = GridBagConstraints.NORTH;
   gbPanel4.setConstraints(btBut0, gbcPanel4);
   pnPanel4.add(btBut0);

   btBut1 = new JButton("Check Image");
   gbcPanel4.gridx = 0;
   gbcPanel4.gridy = 8;
   gbcPanel4.gridwidth = 6;
   gbcPanel4.gridheight = 3;
   gbcPanel4.fill = GridBagConstraints.BOTH;
   gbcPanel4.weightx = 1;
   gbcPanel4.weighty = 0;
   gbcPanel4.anchor = GridBagConstraints.NORTH;
   gbPanel4.setConstraints(btBut1, gbcPanel4);
   pnPanel4.add(btBut1);
   sppSplitPane1.setLeftComponent(pnPanel4);

   pnPanel5 = new JPanel();
   GridBagLayout gbPanel5 = new GridBagLayout();
   GridBagConstraints gbcPanel5 = new GridBagConstraints();
   pnPanel5.setLayout(gbPanel5);

   pnPanel6 = new JPanel();
   GridBagLayout gbPanel6 = new GridBagLayout();
   GridBagConstraints gbcPanel6 = new GridBagConstraints();
   pnPanel6.setLayout(gbPanel6);
   gbcPanel5.gridx = 0;
   gbcPanel5.gridy = 0;
   gbcPanel5.gridwidth = 10;
   gbcPanel5.gridheight = 12;
   gbcPanel5.fill = GridBagConstraints.BOTH;
   gbcPanel5.weightx = 1;
   gbcPanel5.weighty = 0;
   gbcPanel5.anchor = GridBagConstraints.NORTH;
   gbPanel5.setConstraints(pnPanel6, gbcPanel5);
   pnPanel5.add(pnPanel6);

   taArea0 = new JTextArea(2,10);
   JScrollPane scpArea0 = new JScrollPane(taArea0);
   gbcPanel5.gridx = 0;
   gbcPanel5.gridy = 12;
   gbcPanel5.gridwidth = 10;
   gbcPanel5.gridheight = 4;
   gbcPanel5.fill = GridBagConstraints.BOTH;
   gbcPanel5.weightx = 1;
   gbcPanel5.weighty = 1;
   gbcPanel5.anchor = GridBagConstraints.NORTH;
   gbPanel5.setConstraints(scpArea0, gbcPanel5);
   pnPanel5.add(scpArea0);
   sppSplitPane1.setRightComponent(pnPanel5);
   gbcPanel0.gridx = 0;
   gbcPanel0.gridy = 1;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 1;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints(sppSplitPane1, gbcPanel0);
   pnPanel0.add(sppSplitPane1);

   taArea1 = new JTextArea(2,10);
   gbcPanel0.gridx = 0;
   gbcPanel0.gridy = 0;
   gbcPanel0.gridwidth = 1;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 1;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints(taArea1, gbcPanel0);
   pnPanel0.add(taArea1);

   setDefaultCloseOperation(EXIT_ON_CLOSE);

   setContentPane(pnPanel0);
   pack();
   setVisible(true);
} 
} 
